### ISSUE TITLE
Stuck in python command after missing parameter error

### ISSUE THREAD

**Issue by HashtagMarkus** [bats3c/shad0w#45] opened 2020-09-21 22:18 UTC
Steps to reproduce: 
- Interact with an active beacon
- Enter: `execute` -> A error message is displayed
- Enter `execute` again -> The message is shown two times
- Enter a valid command -> The `error_list` variable is not cleared which leads to the same error messages as before

Example:
```
shad0w(az500@c2test) ≫ execute
the following arguments are required: -f/--file
...

shad0w(az500@c2test) ≫ execute
the following arguments are required: -f/--file
the following arguments are required: -f/--file
...

shad0w(az500@c2test) ≫ execute -f msg.exe -p hello world
the following arguments are required: -f/--file
the following arguments are required: -f/--file
```

I noticed this in the following commands:
- `execute`
- `shinject` 
- `rubeus` 
- `hijack`
- `dllinject`
- `binject`

Seems to work without this issue: (Not sure yet why this behaves different)
- `mimikatz`

**Comment by bats3c** [comment] 2020-09-21 22:25
I believe this is the cause of issue #29 which was been incorrectly closed. But rather than reopening I will use this issue to track the fix as this bug is in a lot of modules.

**Comment by HashtagMarkus** [comment] 2020-09-22 14:09
Proposal for a refactoring of the commands which would also fix this issue

https://github.com/bats3c/shad0w/compare/master...HashtagMarkus:dev?expand=1

I created basecommand.py class and as an example refactored execute.py to inherit from BaseCommand.
This way the parsing and error handling would be handled in a single point (base) and the concrete command implementation only provides plain functionality and description. 
I could go further in that direction, but since it's quite a big refactoring touching all commands I'd rather get your opinion on that first ;-)

**Comment by HashtagMarkus** [comment] 2020-09-23 20:27
Refactored all above mentioned commands first. (See #48 ) If accepted, I'd refactor the other commands in a separate PR to keep things small

**Comment by bats3c** [comment] 2020-09-24 09:35
Accepted #48. This should be fixed now.

**Closed by bats3c** 2020-09-24 09:35 UTC
